CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER PRIMARY KEY,
    player_nickname TEXT,
    country TEXT,
    real_name TEXT,
    age INTEGER,
    current_team TEXT,
    prize_money REAL,
    maps_past3 INTEGER,
    rating_2_1 REAL,
    firepower REAL,
    entrying REAL,
    trading REAL,
    opening REAL,
    clutching REAL,
    sniping REAL,
    utility REAL,
    teams_count INTEGER,
    days_in_current_team INTEGER,
    days_in_teams INTEGER,
    majors_played INTEGER,
    majors_won INTEGER,
    lans_played INTEGER,
    lans_won INTEGER,
    faceit_url TEXT,
    faceit_matches INTEGER,
    faceit_winrate REAL,
    faceit_winstreak INTEGER,
    faceit_avgkdr REAL,
    faceit_headshots REAL,
    next_update TIMESTAMP,
    last_update TIMESTAMP
); 